default_language_version:
  python: python3.13

repos:
  - repo: local
    hooks:
      - id: migrations-check
        name: Check migrations
        entry: sh -c "./manage.py makemigrations --check --dry-run"
        files: ^.*/models\.py$
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: name-tests-test
        args: [--django]
      - id: check-yaml
        exclude: ^(.*)/(fixtures|test-fixtures)/.*$
      - id: requirements-txt-fixer
        files: ^requirements.*\.txt$

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--line-length=80]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile, black, --line-length=80]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [-i, -r, --black]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, -ll]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
          - flake8-pie
          - flake8-print
          - flake8-useless-assert
          - flake8-builtins
          - flake8-assertive
          - radon
          - dlint
        args: [--max-line-length=80, --radon-max-cc=12, --radon-show-closures, --max-doc-length=130, "--ignore=E501,A003,DUO102,E402,W503,PIE786,PIE783"]
